/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableMap
 *  com.google.common.collect.ImmutableMap$Builder
 *  net.fabricmc.api.EnvType
 *  net.fabricmc.api.Environment
 */
package net.minecraft.client.model.geom;

import com.google.common.collect.ImmutableMap;
import java.util.List;
import java.util.Map;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.model.ambient.BatModel;
import net.minecraft.client.model.animal.allay.AllayModel;
import net.minecraft.client.model.animal.armadillo.ArmadilloModel;
import net.minecraft.client.model.animal.axolotl.AxolotlModel;
import net.minecraft.client.model.animal.bee.BeeModel;
import net.minecraft.client.model.animal.bee.BeeStingerModel;
import net.minecraft.client.model.animal.camel.CamelModel;
import net.minecraft.client.model.animal.camel.CamelSaddleModel;
import net.minecraft.client.model.animal.chicken.ChickenModel;
import net.minecraft.client.model.animal.chicken.ColdChickenModel;
import net.minecraft.client.model.animal.cow.ColdCowModel;
import net.minecraft.client.model.animal.cow.CowModel;
import net.minecraft.client.model.animal.cow.WarmCowModel;
import net.minecraft.client.model.animal.dolphin.DolphinModel;
import net.minecraft.client.model.animal.equine.AbstractEquineModel;
import net.minecraft.client.model.animal.equine.DonkeyModel;
import net.minecraft.client.model.animal.equine.EquineSaddleModel;
import net.minecraft.client.model.animal.feline.CatModel;
import net.minecraft.client.model.animal.feline.FelineModel;
import net.minecraft.client.model.animal.fish.CodModel;
import net.minecraft.client.model.animal.fish.PufferfishBigModel;
import net.minecraft.client.model.animal.fish.PufferfishMidModel;
import net.minecraft.client.model.animal.fish.PufferfishSmallModel;
import net.minecraft.client.model.animal.fish.SalmonModel;
import net.minecraft.client.model.animal.fish.TropicalFishLargeModel;
import net.minecraft.client.model.animal.fish.TropicalFishSmallModel;
import net.minecraft.client.model.animal.fox.FoxModel;
import net.minecraft.client.model.animal.frog.FrogModel;
import net.minecraft.client.model.animal.frog.TadpoleModel;
import net.minecraft.client.model.animal.ghast.HappyGhastHarnessModel;
import net.minecraft.client.model.animal.ghast.HappyGhastModel;
import net.minecraft.client.model.animal.goat.GoatModel;
import net.minecraft.client.model.animal.golem.CopperGolemModel;
import net.minecraft.client.model.animal.golem.IronGolemModel;
import net.minecraft.client.model.animal.golem.SnowGolemModel;
import net.minecraft.client.model.animal.llama.LlamaModel;
import net.minecraft.client.model.animal.llama.LlamaSpitModel;
import net.minecraft.client.model.animal.nautilus.NautilusArmorModel;
import net.minecraft.client.model.animal.nautilus.NautilusModel;
import net.minecraft.client.model.animal.nautilus.NautilusSaddleModel;
import net.minecraft.client.model.animal.panda.PandaModel;
import net.minecraft.client.model.animal.parrot.ParrotModel;
import net.minecraft.client.model.animal.pig.ColdPigModel;
import net.minecraft.client.model.animal.pig.PigModel;
import net.minecraft.client.model.animal.polarbear.PolarBearModel;
import net.minecraft.client.model.animal.rabbit.RabbitModel;
import net.minecraft.client.model.animal.sheep.SheepFurModel;
import net.minecraft.client.model.animal.sheep.SheepModel;
import net.minecraft.client.model.animal.sniffer.SnifferModel;
import net.minecraft.client.model.animal.squid.SquidModel;
import net.minecraft.client.model.animal.turtle.TurtleModel;
import net.minecraft.client.model.animal.wolf.WolfModel;
import net.minecraft.client.model.effects.EvokerFangsModel;
import net.minecraft.client.model.effects.SpinAttackEffectModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelLayers;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshTransformer;
import net.minecraft.client.model.monster.blaze.BlazeModel;
import net.minecraft.client.model.monster.breeze.BreezeModel;
import net.minecraft.client.model.monster.creaking.CreakingModel;
import net.minecraft.client.model.monster.creeper.CreeperModel;
import net.minecraft.client.model.monster.dragon.EnderDragonModel;
import net.minecraft.client.model.monster.enderman.EndermanModel;
import net.minecraft.client.model.monster.endermite.EndermiteModel;
import net.minecraft.client.model.monster.ghast.GhastModel;
import net.minecraft.client.model.monster.guardian.GuardianModel;
import net.minecraft.client.model.monster.hoglin.HoglinModel;
import net.minecraft.client.model.monster.illager.IllagerModel;
import net.minecraft.client.model.monster.nautilus.ZombieNautilusCoralModel;
import net.minecraft.client.model.monster.phantom.PhantomModel;
import net.minecraft.client.model.monster.piglin.PiglinModel;
import net.minecraft.client.model.monster.ravager.RavagerModel;
import net.minecraft.client.model.monster.shulker.ShulkerModel;
import net.minecraft.client.model.monster.silverfish.SilverfishModel;
import net.minecraft.client.model.monster.skeleton.BoggedModel;
import net.minecraft.client.model.monster.skeleton.SkeletonModel;
import net.minecraft.client.model.monster.slime.MagmaCubeModel;
import net.minecraft.client.model.monster.slime.SlimeModel;
import net.minecraft.client.model.monster.spider.SpiderModel;
import net.minecraft.client.model.monster.strider.StriderModel;
import net.minecraft.client.model.monster.vex.VexModel;
import net.minecraft.client.model.monster.warden.WardenModel;
import net.minecraft.client.model.monster.witch.WitchModel;
import net.minecraft.client.model.monster.wither.WitherBossModel;
import net.minecraft.client.model.monster.zombie.DrownedModel;
import net.minecraft.client.model.monster.zombie.ZombieVillagerModel;
import net.minecraft.client.model.npc.VillagerModel;
import net.minecraft.client.model.object.armorstand.ArmorStandArmorModel;
import net.minecraft.client.model.object.armorstand.ArmorStandModel;
import net.minecraft.client.model.object.banner.BannerFlagModel;
import net.minecraft.client.model.object.banner.BannerModel;
import net.minecraft.client.model.object.bell.BellModel;
import net.minecraft.client.model.object.boat.BoatModel;
import net.minecraft.client.model.object.boat.RaftModel;
import net.minecraft.client.model.object.book.BookModel;
import net.minecraft.client.model.object.cart.MinecartModel;
import net.minecraft.client.model.object.chest.ChestModel;
import net.minecraft.client.model.object.crystal.EndCrystalModel;
import net.minecraft.client.model.object.equipment.ElytraModel;
import net.minecraft.client.model.object.equipment.ShieldModel;
import net.minecraft.client.model.object.leash.LeashKnotModel;
import net.minecraft.client.model.object.projectile.ArrowModel;
import net.minecraft.client.model.object.projectile.ShulkerBulletModel;
import net.minecraft.client.model.object.projectile.TridentModel;
import net.minecraft.client.model.object.projectile.WindChargeModel;
import net.minecraft.client.model.object.skull.DragonHeadModel;
import net.minecraft.client.model.object.skull.PiglinHeadModel;
import net.minecraft.client.model.object.skull.SkullModel;
import net.minecraft.client.model.player.PlayerCapeModel;
import net.minecraft.client.model.player.PlayerEarsModel;
import net.minecraft.client.model.player.PlayerModel;
import net.minecraft.client.renderer.blockentity.BedRenderer;
import net.minecraft.client.renderer.blockentity.ConduitRenderer;
import net.minecraft.client.renderer.blockentity.DecoratedPotRenderer;
import net.minecraft.client.renderer.blockentity.HangingSignRenderer;
import net.minecraft.client.renderer.blockentity.SignRenderer;
import net.minecraft.client.renderer.entity.ArmorModelSet;
import net.minecraft.client.renderer.entity.WitherSkullRenderer;
import net.minecraft.world.level.block.state.properties.WoodType;

@Environment(value=EnvType.CLIENT)
public class LayerDefinitions {
    private static final CubeDeformation FISH_PATTERN_DEFORMATION = new CubeDeformation(0.008f);
    private static final CubeDeformation OUTER_ARMOR_DEFORMATION = new CubeDeformation(1.0f);
    private static final CubeDeformation INNER_ARMOR_DEFORMATION = new CubeDeformation(0.5f);

    public static Map<ModelLayerLocation, LayerDefinition> createRoots() {
        ImmutableMap.Builder builder = ImmutableMap.builder();
        LayerDefinition layerDefinition2 = LayerDefinition.create(HumanoidModel.createMesh(CubeDeformation.NONE, 0.0f), 64, 64);
        ArmorModelSet<LayerDefinition> armorModelSet = HumanoidModel.createArmorMeshSet(INNER_ARMOR_DEFORMATION, OUTER_ARMOR_DEFORMATION).map(meshDefinition -> LayerDefinition.create(meshDefinition, 64, 32));
        ArmorModelSet<LayerDefinition> armorModelSet2 = armorModelSet.map(layerDefinition -> layerDefinition.apply(HumanoidModel.BABY_TRANSFORMER));
        ArmorModelSet<LayerDefinition> armorModelSet3 = PlayerModel.createArmorMeshSet(INNER_ARMOR_DEFORMATION, OUTER_ARMOR_DEFORMATION).map(meshDefinition -> LayerDefinition.create(meshDefinition, 64, 32));
        ArmorModelSet<LayerDefinition> armorModelSet4 = PiglinModel.createArmorMeshSet(INNER_ARMOR_DEFORMATION, new CubeDeformation(1.02f)).map(meshDefinition -> LayerDefinition.create(meshDefinition, 64, 32));
        ArmorModelSet<LayerDefinition> armorModelSet5 = armorModelSet4.map(layerDefinition -> layerDefinition.apply(HumanoidModel.BABY_TRANSFORMER));
        LayerDefinition layerDefinition22 = MinecartModel.createBodyLayer();
        LayerDefinition layerDefinition3 = SkullModel.createMobHeadLayer();
        LayerDefinition layerDefinition4 = LayerDefinition.create(AbstractEquineModel.createBodyMesh(CubeDeformation.NONE), 64, 64);
        LayerDefinition layerDefinition5 = LayerDefinition.create(AbstractEquineModel.createBabyMesh(CubeDeformation.NONE), 64, 64);
        LayerDefinition layerDefinition6 = EquineSaddleModel.createSaddleLayer(false);
        LayerDefinition layerDefinition7 = EquineSaddleModel.createSaddleLayer(true);
        MeshTransformer meshTransformer = MeshTransformer.scaling(0.9375f);
        LayerDefinition layerDefinition8 = IllagerModel.createBodyLayer().apply(meshTransformer);
        LayerDefinition layerDefinition9 = AxolotlModel.createBodyLayer();
        LayerDefinition layerDefinition10 = BeeModel.createBodyLayer();
        LayerDefinition layerDefinition11 = CowModel.createBodyLayer();
        LayerDefinition layerDefinition12 = ColdChickenModel.createBodyLayer();
        LayerDefinition layerDefinition13 = ColdCowModel.createBodyLayer();
        LayerDefinition layerDefinition14 = ColdPigModel.createBodyLayer(CubeDeformation.NONE);
        LayerDefinition layerDefinition15 = ElytraModel.createLayer();
        LayerDefinition layerDefinition16 = LayerDefinition.create(FelineModel.createBodyMesh(CubeDeformation.NONE), 64, 32);
        LayerDefinition layerDefinition17 = layerDefinition16.apply(FelineModel.BABY_TRANSFORMER);
        LayerDefinition layerDefinition18 = LayerDefinition.create(FelineModel.createBodyMesh(new CubeDeformation(0.01f)), 64, 32);
        LayerDefinition layerDefinition19 = LayerDefinition.create(PiglinModel.createMesh(CubeDeformation.NONE), 64, 64);
        LayerDefinition layerDefinition20 = LayerDefinition.create(PiglinHeadModel.createHeadModel(), 64, 64);
        LayerDefinition layerDefinition21 = SkullModel.createHumanoidHeadLayer();
        LayerDefinition layerDefinition222 = LlamaModel.createBodyLayer(CubeDeformation.NONE);
        LayerDefinition layerDefinition23 = LlamaModel.createBodyLayer(new CubeDeformation(0.5f));
        LayerDefinition layerDefinition24 = StriderModel.createBodyLayer();
        LayerDefinition layerDefinition25 = HoglinModel.createBodyLayer();
        LayerDefinition layerDefinition26 = HoglinModel.createBabyLayer();
        LayerDefinition layerDefinition27 = SkeletonModel.createBodyLayer();
        LayerDefinition layerDefinition28 = LayerDefinition.create(VillagerModel.createBodyModel(), 64, 64).apply(meshTransformer);
        LayerDefinition layerDefinition29 = LayerDefinition.create(VillagerModel.createNoHatModel(), 64, 64).apply(meshTransformer);
        LayerDefinition layerDefinition30 = SpiderModel.createSpiderBodyLayer();
        LayerDefinition layerDefinition31 = ArmadilloModel.createBodyLayer();
        LayerDefinition layerDefinition32 = CamelModel.createBodyLayer();
        LayerDefinition layerDefinition33 = CamelSaddleModel.createSaddleLayer();
        LayerDefinition layerDefinition34 = ChickenModel.createBodyLayer();
        LayerDefinition layerDefinition35 = GoatModel.createBodyLayer();
        LayerDefinition layerDefinition36 = PandaModel.createBodyLayer();
        LayerDefinition layerDefinition37 = PigModel.createBodyLayer(CubeDeformation.NONE);
        LayerDefinition layerDefinition38 = PigModel.createBodyLayer(new CubeDeformation(0.5f));
        LayerDefinition layerDefinition39 = SheepModel.createBodyLayer();
        LayerDefinition layerDefinition40 = SheepFurModel.createFurLayer();
        LayerDefinition layerDefinition41 = SnifferModel.createBodyLayer();
        LayerDefinition layerDefinition42 = TurtleModel.createBodyLayer();
        LayerDefinition layerDefinition43 = WarmCowModel.createBodyLayer();
        LayerDefinition layerDefinition44 = LayerDefinition.create(WolfModel.createMeshDefinition(CubeDeformation.NONE), 64, 32);
        LayerDefinition layerDefinition45 = LayerDefinition.create(WolfModel.createMeshDefinition(new CubeDeformation(0.2f)), 64, 32);
        LayerDefinition layerDefinition46 = ZombieVillagerModel.createBodyLayer();
        LayerDefinition layerDefinition47 = ZombieVillagerModel.createNoHatLayer();
        LayerDefinition layerDefinition48 = ArmorStandModel.createBodyLayer();
        ArmorModelSet<LayerDefinition> armorModelSet6 = ArmorStandArmorModel.createArmorLayerSet(INNER_ARMOR_DEFORMATION, OUTER_ARMOR_DEFORMATION);
        LayerDefinition layerDefinition49 = DrownedModel.createBodyLayer(CubeDeformation.NONE);
        LayerDefinition layerDefinition50 = DrownedModel.createBodyLayer(new CubeDeformation(0.25f));
        LayerDefinition layerDefinition51 = SquidModel.createBodyLayer();
        LayerDefinition layerDefinition52 = DolphinModel.createBodyLayer();
        LayerDefinition layerDefinition53 = SalmonModel.createBodyLayer();
        LayerDefinition layerDefinition54 = NautilusSaddleModel.createSaddleLayer();
        builder.put((Object)ModelLayers.ALLAY, (Object)AllayModel.createBodyLayer());
        builder.put((Object)ModelLayers.ARMADILLO, (Object)layerDefinition31);
        builder.put((Object)ModelLayers.ARMADILLO_BABY, (Object)layerDefinition31.apply(ArmadilloModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.ARMOR_STAND, (Object)layerDefinition48);
        ModelLayers.ARMOR_STAND_ARMOR.putFrom(armorModelSet6, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)builder);
        builder.put((Object)ModelLayers.ARMOR_STAND_SMALL, (Object)layerDefinition48.apply(HumanoidModel.BABY_TRANSFORMER));
        ModelLayers.ARMOR_STAND_SMALL_ARMOR.putFrom(armorModelSet6.map(layerDefinition -> layerDefinition.apply(HumanoidModel.BABY_TRANSFORMER)), (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)builder);
        builder.put((Object)ModelLayers.ARROW, (Object)ArrowModel.createBodyLayer());
        builder.put((Object)ModelLayers.AXOLOTL, (Object)layerDefinition9);
        builder.put((Object)ModelLayers.AXOLOTL_BABY, (Object)layerDefinition9.apply(AxolotlModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.STANDING_BANNER, (Object)BannerModel.createBodyLayer(true));
        builder.put((Object)ModelLayers.WALL_BANNER, (Object)BannerModel.createBodyLayer(false));
        builder.put((Object)ModelLayers.STANDING_BANNER_FLAG, (Object)BannerFlagModel.createFlagLayer(true));
        builder.put((Object)ModelLayers.WALL_BANNER_FLAG, (Object)BannerFlagModel.createFlagLayer(false));
        builder.put((Object)ModelLayers.BAT, (Object)BatModel.createBodyLayer());
        builder.put((Object)ModelLayers.BED_FOOT, (Object)BedRenderer.createFootLayer());
        builder.put((Object)ModelLayers.BED_HEAD, (Object)BedRenderer.createHeadLayer());
        builder.put((Object)ModelLayers.BEE, (Object)layerDefinition10);
        builder.put((Object)ModelLayers.BEE_BABY, (Object)layerDefinition10.apply(BeeModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.BEE_STINGER, (Object)BeeStingerModel.createBodyLayer());
        builder.put((Object)ModelLayers.BELL, (Object)BellModel.createBodyLayer());
        builder.put((Object)ModelLayers.BLAZE, (Object)BlazeModel.createBodyLayer());
        builder.put((Object)ModelLayers.BOAT_WATER_PATCH, (Object)BoatModel.createWaterPatch());
        builder.put((Object)ModelLayers.BOGGED, (Object)BoggedModel.createBodyLayer());
        ModelLayers.BOGGED_ARMOR.putFrom(armorModelSet, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)builder);
        builder.put((Object)ModelLayers.BOGGED_OUTER_LAYER, (Object)LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.2f), 0.0f), 64, 32));
        builder.put((Object)ModelLayers.BOOK, (Object)BookModel.createBodyLayer());
        builder.put((Object)ModelLayers.BREEZE, (Object)BreezeModel.createBodyLayer());
        builder.put((Object)ModelLayers.BREEZE_WIND, (Object)BreezeModel.createWindLayer());
        builder.put((Object)ModelLayers.BREEZE_EYES, (Object)BreezeModel.createEyesLayer());
        builder.put((Object)ModelLayers.CAT, (Object)layerDefinition16.apply(CatModel.CAT_TRANSFORMER));
        builder.put((Object)ModelLayers.CAT_BABY, (Object)layerDefinition17.apply(CatModel.CAT_TRANSFORMER));
        builder.put((Object)ModelLayers.CAT_COLLAR, (Object)layerDefinition18.apply(CatModel.CAT_TRANSFORMER));
        builder.put((Object)ModelLayers.CAT_BABY_COLLAR, (Object)layerDefinition18.apply(FelineModel.BABY_TRANSFORMER).apply(CatModel.CAT_TRANSFORMER));
        builder.put((Object)ModelLayers.CAMEL, (Object)layerDefinition32);
        builder.put((Object)ModelLayers.CAMEL_BABY, (Object)layerDefinition32.apply(CamelModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.CAMEL_SADDLE, (Object)layerDefinition33);
        builder.put((Object)ModelLayers.CAMEL_BABY_SADDLE, (Object)layerDefinition33.apply(CamelModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.CAMEL_HUSK_SADDLE, (Object)layerDefinition33);
        builder.put((Object)ModelLayers.CAMEL_HUSK_BABY_SADDLE, (Object)layerDefinition33.apply(CamelModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.CAVE_SPIDER, (Object)layerDefinition30.apply(MeshTransformer.scaling(0.7f)));
        builder.put((Object)ModelLayers.CHEST, (Object)ChestModel.createSingleBodyLayer());
        builder.put((Object)ModelLayers.CHEST_MINECART, (Object)layerDefinition22);
        builder.put((Object)ModelLayers.CHICKEN, (Object)layerDefinition34);
        builder.put((Object)ModelLayers.CHICKEN_BABY, (Object)layerDefinition34.apply(ChickenModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.COD, (Object)CodModel.createBodyLayer());
        builder.put((Object)ModelLayers.COLD_CHICKEN, (Object)layerDefinition12);
        builder.put((Object)ModelLayers.COLD_CHICKEN_BABY, (Object)layerDefinition12.apply(ChickenModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.COLD_COW, (Object)layerDefinition13);
        builder.put((Object)ModelLayers.COLD_COW_BABY, (Object)layerDefinition13.apply(CowModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.COLD_PIG, (Object)layerDefinition14);
        builder.put((Object)ModelLayers.COLD_PIG_BABY, (Object)layerDefinition14.apply(PigModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.COMMAND_BLOCK_MINECART, (Object)layerDefinition22);
        builder.put((Object)ModelLayers.CONDUIT_EYE, (Object)ConduitRenderer.createEyeLayer());
        builder.put((Object)ModelLayers.CONDUIT_WIND, (Object)ConduitRenderer.createWindLayer());
        builder.put((Object)ModelLayers.CONDUIT_SHELL, (Object)ConduitRenderer.createShellLayer());
        builder.put((Object)ModelLayers.CONDUIT_CAGE, (Object)ConduitRenderer.createCageLayer());
        builder.put((Object)ModelLayers.COPPER_GOLEM, (Object)CopperGolemModel.createBodyLayer());
        builder.put((Object)ModelLayers.COPPER_GOLEM_EYES, (Object)CopperGolemModel.createEyesLayer());
        builder.put((Object)ModelLayers.COPPER_GOLEM_RUNNING, (Object)CopperGolemModel.createRunningPoseBodyLayer());
        builder.put((Object)ModelLayers.COPPER_GOLEM_SITTING, (Object)CopperGolemModel.createSittingPoseBodyLayer());
        builder.put((Object)ModelLayers.COPPER_GOLEM_STAR, (Object)CopperGolemModel.createStarPoseBodyLayer());
        builder.put((Object)ModelLayers.COW, (Object)layerDefinition11);
        builder.put((Object)ModelLayers.COW_BABY, (Object)layerDefinition11.apply(CowModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.CREAKING, (Object)CreakingModel.createBodyLayer());
        builder.put((Object)ModelLayers.CREAKING_EYES, (Object)CreakingModel.createEyesLayer());
        builder.put((Object)ModelLayers.CREEPER, (Object)CreeperModel.createBodyLayer(CubeDeformation.NONE));
        builder.put((Object)ModelLayers.CREEPER_ARMOR, (Object)CreeperModel.createBodyLayer(new CubeDeformation(2.0f)));
        builder.put((Object)ModelLayers.CREEPER_HEAD, (Object)layerDefinition3);
        builder.put((Object)ModelLayers.DECORATED_POT_BASE, (Object)DecoratedPotRenderer.createBaseLayer());
        builder.put((Object)ModelLayers.DECORATED_POT_SIDES, (Object)DecoratedPotRenderer.createSidesLayer());
        builder.put((Object)ModelLayers.DOLPHIN, (Object)layerDefinition52);
        builder.put((Object)ModelLayers.DOLPHIN_BABY, (Object)layerDefinition52.apply(DolphinModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.DONKEY, (Object)DonkeyModel.createBodyLayer(0.87f));
        builder.put((Object)ModelLayers.DONKEY_BABY, (Object)DonkeyModel.createBabyLayer(0.87f));
        builder.put((Object)ModelLayers.DONKEY_SADDLE, (Object)DonkeyModel.createSaddleLayer(0.87f, false));
        builder.put((Object)ModelLayers.DONKEY_BABY_SADDLE, (Object)DonkeyModel.createSaddleLayer(0.87f, true));
        builder.put((Object)ModelLayers.DOUBLE_CHEST_LEFT, (Object)ChestModel.createDoubleBodyLeftLayer());
        builder.put((Object)ModelLayers.DOUBLE_CHEST_RIGHT, (Object)ChestModel.createDoubleBodyRightLayer());
        builder.put((Object)ModelLayers.DRAGON_SKULL, (Object)DragonHeadModel.createHeadLayer());
        builder.put((Object)ModelLayers.DROWNED, (Object)layerDefinition49);
        ModelLayers.DROWNED_ARMOR.putFrom(armorModelSet, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)builder);
        builder.put((Object)ModelLayers.DROWNED_OUTER_LAYER, (Object)layerDefinition50);
        builder.put((Object)ModelLayers.DROWNED_BABY, (Object)layerDefinition49.apply(HumanoidModel.BABY_TRANSFORMER));
        ModelLayers.DROWNED_BABY_ARMOR.putFrom(armorModelSet2, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)builder);
        builder.put((Object)ModelLayers.DROWNED_BABY_OUTER_LAYER, (Object)layerDefinition50.apply(HumanoidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.ELDER_GUARDIAN, (Object)GuardianModel.createElderGuardianLayer());
        builder.put((Object)ModelLayers.ELYTRA, (Object)layerDefinition15);
        builder.put((Object)ModelLayers.ELYTRA_BABY, (Object)layerDefinition15.apply(ElytraModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.ENDERMAN, (Object)EndermanModel.createBodyLayer());
        builder.put((Object)ModelLayers.ENDERMITE, (Object)EndermiteModel.createBodyLayer());
        builder.put((Object)ModelLayers.ENDER_DRAGON, (Object)EnderDragonModel.createBodyLayer());
        builder.put((Object)ModelLayers.END_CRYSTAL, (Object)EndCrystalModel.createBodyLayer());
        builder.put((Object)ModelLayers.EVOKER, (Object)layerDefinition8);
        builder.put((Object)ModelLayers.EVOKER_FANGS, (Object)EvokerFangsModel.createBodyLayer());
        builder.put((Object)ModelLayers.FOX, (Object)FoxModel.createBodyLayer());
        builder.put((Object)ModelLayers.FOX_BABY, (Object)FoxModel.createBodyLayer().apply(FoxModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.FROG, (Object)FrogModel.createBodyLayer());
        builder.put((Object)ModelLayers.FURNACE_MINECART, (Object)layerDefinition22);
        builder.put((Object)ModelLayers.GHAST, (Object)GhastModel.createBodyLayer());
        MeshTransformer meshTransformer2 = MeshTransformer.scaling(6.0f);
        builder.put((Object)ModelLayers.GIANT, (Object)layerDefinition2.apply(meshTransformer2));
        ModelLayers.GIANT_ARMOR.putFrom(armorModelSet.map(layerDefinition -> layerDefinition.apply(meshTransformer2)), (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)builder);
        builder.put((Object)ModelLayers.GLOW_SQUID, (Object)layerDefinition51);
        builder.put((Object)ModelLayers.GLOW_SQUID_BABY, (Object)layerDefinition51.apply(SquidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.GOAT, (Object)layerDefinition35);
        builder.put((Object)ModelLayers.GOAT_BABY, (Object)layerDefinition35.apply(GoatModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.GUARDIAN, (Object)GuardianModel.createBodyLayer());
        builder.put((Object)ModelLayers.HAPPY_GHAST, (Object)HappyGhastModel.createBodyLayer(false, CubeDeformation.NONE));
        builder.put((Object)ModelLayers.HAPPY_GHAST_BABY, (Object)HappyGhastModel.createBodyLayer(true, CubeDeformation.NONE).apply(HappyGhastModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.HAPPY_GHAST_HARNESS, (Object)HappyGhastHarnessModel.createHarnessLayer(false));
        builder.put((Object)ModelLayers.HAPPY_GHAST_BABY_HARNESS, (Object)HappyGhastHarnessModel.createHarnessLayer(true).apply(HappyGhastModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.HAPPY_GHAST_ROPES, (Object)HappyGhastModel.createBodyLayer(false, new CubeDeformation(0.2f)));
        builder.put((Object)ModelLayers.HAPPY_GHAST_BABY_ROPES, (Object)HappyGhastModel.createBodyLayer(true, new CubeDeformation(0.2f)).apply(HappyGhastModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.HOGLIN, (Object)layerDefinition25);
        builder.put((Object)ModelLayers.HOGLIN_BABY, (Object)layerDefinition26);
        builder.put((Object)ModelLayers.HOPPER_MINECART, (Object)layerDefinition22);
        MeshTransformer meshTransformer3 = MeshTransformer.scaling(1.1f);
        builder.put((Object)ModelLayers.HORSE, (Object)layerDefinition4.apply(meshTransformer3));
        builder.put((Object)ModelLayers.HORSE_BABY, (Object)layerDefinition5.apply(meshTransformer3));
        builder.put((Object)ModelLayers.HORSE_ARMOR, (Object)LayerDefinition.create(AbstractEquineModel.createBodyMesh(new CubeDeformation(0.1f)), 64, 64).apply(meshTransformer3));
        builder.put((Object)ModelLayers.HORSE_BABY_ARMOR, (Object)LayerDefinition.create(AbstractEquineModel.createBabyMesh(new CubeDeformation(0.1f)), 64, 64).apply(meshTransformer3));
        builder.put((Object)ModelLayers.HORSE_SADDLE, (Object)layerDefinition6.apply(meshTransformer3));
        builder.put((Object)ModelLayers.HORSE_BABY_SADDLE, (Object)layerDefinition7.apply(meshTransformer3));
        MeshTransformer meshTransformer4 = MeshTransformer.scaling(1.0625f);
        builder.put((Object)ModelLayers.HUSK, (Object)layerDefinition2.apply(meshTransformer4));
        ModelLayers.HUSK_ARMOR.putFrom(armorModelSet.map(layerDefinition -> layerDefinition.apply(meshTransformer4)), (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)builder);
        builder.put((Object)ModelLayers.HUSK_BABY, (Object)layerDefinition2.apply(HumanoidModel.BABY_TRANSFORMER).apply(meshTransformer4));
        ModelLayers.HUSK_BABY_ARMOR.putFrom(armorModelSet2.map(layerDefinition -> layerDefinition.apply(meshTransformer4)), (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)builder);
        builder.put((Object)ModelLayers.ILLUSIONER, (Object)layerDefinition8);
        builder.put((Object)ModelLayers.IRON_GOLEM, (Object)IronGolemModel.createBodyLayer());
        builder.put((Object)ModelLayers.LEASH_KNOT, (Object)LeashKnotModel.createBodyLayer());
        builder.put((Object)ModelLayers.LLAMA, (Object)layerDefinition222);
        builder.put((Object)ModelLayers.LLAMA_BABY, (Object)layerDefinition222.apply(LlamaModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.LLAMA_DECOR, (Object)layerDefinition23);
        builder.put((Object)ModelLayers.LLAMA_BABY_DECOR, (Object)layerDefinition23.apply(LlamaModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.LLAMA_SPIT, (Object)LlamaSpitModel.createBodyLayer());
        builder.put((Object)ModelLayers.MAGMA_CUBE, (Object)MagmaCubeModel.createBodyLayer());
        builder.put((Object)ModelLayers.MINECART, (Object)layerDefinition22);
        builder.put((Object)ModelLayers.MOOSHROOM, (Object)layerDefinition11);
        builder.put((Object)ModelLayers.MOOSHROOM_BABY, (Object)layerDefinition11.apply(CowModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.MULE, (Object)DonkeyModel.createBodyLayer(0.92f));
        builder.put((Object)ModelLayers.MULE_BABY, (Object)DonkeyModel.createBabyLayer(0.92f));
        builder.put((Object)ModelLayers.MULE_SADDLE, (Object)DonkeyModel.createSaddleLayer(0.92f, false));
        builder.put((Object)ModelLayers.MULE_BABY_SADDLE, (Object)DonkeyModel.createSaddleLayer(0.92f, true));
        builder.put((Object)ModelLayers.NAUTILUS, (Object)NautilusModel.createBodyLayer());
        builder.put((Object)ModelLayers.NAUTILUS_BABY, (Object)NautilusModel.createBabyBodyLayer());
        builder.put((Object)ModelLayers.NAUTILUS_SADDLE, (Object)layerDefinition54);
        builder.put((Object)ModelLayers.NAUTILUS_ARMOR, (Object)NautilusArmorModel.createBodyLayer());
        builder.put((Object)ModelLayers.ZOMBIE_NAUTILUS, (Object)NautilusModel.createBodyLayer());
        builder.put((Object)ModelLayers.ZOMBIE_NAUTILUS_CORAL, (Object)ZombieNautilusCoralModel.createBodyLayer());
        builder.put((Object)ModelLayers.OCELOT, (Object)layerDefinition16);
        builder.put((Object)ModelLayers.OCELOT_BABY, (Object)layerDefinition17);
        builder.put((Object)ModelLayers.PANDA, (Object)layerDefinition36);
        builder.put((Object)ModelLayers.PANDA_BABY, (Object)layerDefinition36.apply(PandaModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.PARCHED, (Object)SkeletonModel.createSingleModelDualBodyLayer());
        ModelLayers.PARCHED_ARMOR.putFrom(armorModelSet, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)builder);
        builder.put((Object)ModelLayers.PARCHED_OUTER_LAYER, (Object)LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.25f), 0.0f), 64, 32));
        builder.put((Object)ModelLayers.PARROT, (Object)ParrotModel.createBodyLayer());
        builder.put((Object)ModelLayers.PHANTOM, (Object)PhantomModel.createBodyLayer());
        builder.put((Object)ModelLayers.PIG, (Object)layerDefinition37);
        builder.put((Object)ModelLayers.PIG_BABY, (Object)layerDefinition37.apply(PigModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.PIG_SADDLE, (Object)layerDefinition38);
        builder.put((Object)ModelLayers.PIG_BABY_SADDLE, (Object)layerDefinition38.apply(PigModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.PIGLIN, (Object)layerDefinition19);
        ModelLayers.PIGLIN_ARMOR.putFrom(armorModelSet4, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)builder);
        builder.put((Object)ModelLayers.PIGLIN_BRUTE, (Object)layerDefinition19);
        ModelLayers.PIGLIN_BRUTE_ARMOR.putFrom(armorModelSet4, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)builder);
        builder.put((Object)ModelLayers.PIGLIN_BABY, (Object)layerDefinition19.apply(HumanoidModel.BABY_TRANSFORMER));
        ModelLayers.PIGLIN_BABY_ARMOR.putFrom(armorModelSet5, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)builder);
        builder.put((Object)ModelLayers.PIGLIN_HEAD, (Object)layerDefinition20);
        builder.put((Object)ModelLayers.PILLAGER, (Object)layerDefinition8);
        builder.put((Object)ModelLayers.PLAYER, (Object)LayerDefinition.create(PlayerModel.createMesh(CubeDeformation.NONE, false), 64, 64));
        builder.put((Object)ModelLayers.PLAYER_EARS, (Object)PlayerEarsModel.createEarsLayer());
        builder.put((Object)ModelLayers.PLAYER_CAPE, (Object)PlayerCapeModel.createCapeLayer());
        builder.put((Object)ModelLayers.PLAYER_HEAD, (Object)layerDefinition21);
        ModelLayers.PLAYER_ARMOR.putFrom(armorModelSet3, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)builder);
        builder.put((Object)ModelLayers.PLAYER_SLIM, (Object)LayerDefinition.create(PlayerModel.createMesh(CubeDeformation.NONE, true), 64, 64));
        ModelLayers.PLAYER_SLIM_ARMOR.putFrom(armorModelSet3, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)builder);
        builder.put((Object)ModelLayers.PLAYER_SPIN_ATTACK, (Object)SpinAttackEffectModel.createLayer());
        builder.put((Object)ModelLayers.POLAR_BEAR, (Object)PolarBearModel.createBodyLayer(false));
        builder.put((Object)ModelLayers.POLAR_BEAR_BABY, (Object)PolarBearModel.createBodyLayer(true));
        builder.put((Object)ModelLayers.PUFFERFISH_BIG, (Object)PufferfishBigModel.createBodyLayer());
        builder.put((Object)ModelLayers.PUFFERFISH_MEDIUM, (Object)PufferfishMidModel.createBodyLayer());
        builder.put((Object)ModelLayers.PUFFERFISH_SMALL, (Object)PufferfishSmallModel.createBodyLayer());
        builder.put((Object)ModelLayers.RABBIT, (Object)RabbitModel.createBodyLayer(false));
        builder.put((Object)ModelLayers.RABBIT_BABY, (Object)RabbitModel.createBodyLayer(true));
        builder.put((Object)ModelLayers.RAVAGER, (Object)RavagerModel.createBodyLayer());
        builder.put((Object)ModelLayers.SALMON, (Object)layerDefinition53);
        builder.put((Object)ModelLayers.SALMON_SMALL, (Object)layerDefinition53.apply(SalmonModel.SMALL_TRANSFORMER));
        builder.put((Object)ModelLayers.SALMON_LARGE, (Object)layerDefinition53.apply(SalmonModel.LARGE_TRANSFORMER));
        builder.put((Object)ModelLayers.SHEEP, (Object)layerDefinition39);
        builder.put((Object)ModelLayers.SHEEP_BABY, (Object)layerDefinition39.apply(SheepModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.SHEEP_WOOL, (Object)layerDefinition40);
        builder.put((Object)ModelLayers.SHEEP_BABY_WOOL, (Object)layerDefinition40.apply(SheepModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.SHEEP_WOOL_UNDERCOAT, (Object)layerDefinition39);
        builder.put((Object)ModelLayers.SHEEP_BABY_WOOL_UNDERCOAT, (Object)layerDefinition39.apply(SheepModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.SHIELD, (Object)ShieldModel.createLayer());
        builder.put((Object)ModelLayers.SHULKER, (Object)ShulkerModel.createBodyLayer());
        builder.put((Object)ModelLayers.SHULKER_BOX, (Object)ShulkerModel.createBoxLayer());
        builder.put((Object)ModelLayers.SHULKER_BULLET, (Object)ShulkerBulletModel.createBodyLayer());
        builder.put((Object)ModelLayers.SILVERFISH, (Object)SilverfishModel.createBodyLayer());
        builder.put((Object)ModelLayers.SKELETON, (Object)layerDefinition27);
        ModelLayers.SKELETON_ARMOR.putFrom(armorModelSet, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)builder);
        builder.put((Object)ModelLayers.SKELETON_HORSE, (Object)layerDefinition4);
        builder.put((Object)ModelLayers.SKELETON_HORSE_BABY, (Object)layerDefinition5);
        builder.put((Object)ModelLayers.SKELETON_HORSE_SADDLE, (Object)layerDefinition6);
        builder.put((Object)ModelLayers.SKELETON_HORSE_BABY_SADDLE, (Object)layerDefinition7);
        builder.put((Object)ModelLayers.SKELETON_SKULL, (Object)layerDefinition3);
        builder.put((Object)ModelLayers.SLIME, (Object)SlimeModel.createInnerBodyLayer());
        builder.put((Object)ModelLayers.SLIME_OUTER, (Object)SlimeModel.createOuterBodyLayer());
        builder.put((Object)ModelLayers.SNIFFER, (Object)layerDefinition41);
        builder.put((Object)ModelLayers.SNIFFER_BABY, (Object)layerDefinition41.apply(SnifferModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.SNOW_GOLEM, (Object)SnowGolemModel.createBodyLayer());
        builder.put((Object)ModelLayers.SPAWNER_MINECART, (Object)layerDefinition22);
        builder.put((Object)ModelLayers.SPIDER, (Object)layerDefinition30);
        builder.put((Object)ModelLayers.SQUID, (Object)layerDefinition51);
        builder.put((Object)ModelLayers.SQUID_BABY, (Object)layerDefinition51.apply(SquidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.STRAY, (Object)layerDefinition27);
        ModelLayers.STRAY_ARMOR.putFrom(armorModelSet, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)builder);
        builder.put((Object)ModelLayers.STRAY_OUTER_LAYER, (Object)LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.25f), 0.0f), 64, 32));
        builder.put((Object)ModelLayers.STRIDER, (Object)layerDefinition24);
        builder.put((Object)ModelLayers.STRIDER_SADDLE, (Object)layerDefinition24);
        builder.put((Object)ModelLayers.STRIDER_BABY, (Object)layerDefinition24.apply(StriderModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.STRIDER_BABY_SADDLE, (Object)layerDefinition24.apply(StriderModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.TADPOLE, (Object)TadpoleModel.createBodyLayer());
        builder.put((Object)ModelLayers.TNT_MINECART, (Object)layerDefinition22);
        builder.put((Object)ModelLayers.TRADER_LLAMA, (Object)layerDefinition222);
        builder.put((Object)ModelLayers.TRADER_LLAMA_BABY, (Object)layerDefinition222.apply(LlamaModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.TRIDENT, (Object)TridentModel.createLayer());
        builder.put((Object)ModelLayers.TROPICAL_FISH_LARGE, (Object)TropicalFishLargeModel.createBodyLayer(CubeDeformation.NONE));
        builder.put((Object)ModelLayers.TROPICAL_FISH_LARGE_PATTERN, (Object)TropicalFishLargeModel.createBodyLayer(FISH_PATTERN_DEFORMATION));
        builder.put((Object)ModelLayers.TROPICAL_FISH_SMALL, (Object)TropicalFishSmallModel.createBodyLayer(CubeDeformation.NONE));
        builder.put((Object)ModelLayers.TROPICAL_FISH_SMALL_PATTERN, (Object)TropicalFishSmallModel.createBodyLayer(FISH_PATTERN_DEFORMATION));
        builder.put((Object)ModelLayers.TURTLE, (Object)layerDefinition42);
        builder.put((Object)ModelLayers.TURTLE_BABY, (Object)layerDefinition42.apply(TurtleModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.UNDEAD_HORSE_ARMOR, (Object)LayerDefinition.create(AbstractEquineModel.createBodyMesh(new CubeDeformation(0.1f)), 64, 64));
        builder.put((Object)ModelLayers.UNDEAD_HORSE_BABY_ARMOR, (Object)LayerDefinition.create(AbstractEquineModel.createBabyMesh(new CubeDeformation(0.1f)), 64, 64));
        builder.put((Object)ModelLayers.VEX, (Object)VexModel.createBodyLayer());
        builder.put((Object)ModelLayers.VILLAGER, (Object)layerDefinition28);
        builder.put((Object)ModelLayers.VILLAGER_NO_HAT, (Object)layerDefinition29);
        builder.put((Object)ModelLayers.VILLAGER_BABY, (Object)layerDefinition28.apply(VillagerModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.VILLAGER_BABY_NO_HAT, (Object)layerDefinition29.apply(VillagerModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.VINDICATOR, (Object)layerDefinition8);
        builder.put((Object)ModelLayers.WARDEN, (Object)WardenModel.createBodyLayer());
        builder.put((Object)ModelLayers.WARDEN_TENDRILS, (Object)WardenModel.createTendrilsLayer());
        builder.put((Object)ModelLayers.WARDEN_HEART, (Object)WardenModel.createHeartLayer());
        builder.put((Object)ModelLayers.WARDEN_BIOLUMINESCENT, (Object)WardenModel.createBioluminescentLayer());
        builder.put((Object)ModelLayers.WARDEN_PULSATING_SPOTS, (Object)WardenModel.createPulsatingSpotsLayer());
        builder.put((Object)ModelLayers.WARM_COW, (Object)layerDefinition43);
        builder.put((Object)ModelLayers.WARM_COW_BABY, (Object)layerDefinition43.apply(CowModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.WANDERING_TRADER, (Object)layerDefinition28);
        builder.put((Object)ModelLayers.WIND_CHARGE, (Object)WindChargeModel.createBodyLayer());
        builder.put((Object)ModelLayers.WITCH, (Object)WitchModel.createBodyLayer().apply(meshTransformer));
        builder.put((Object)ModelLayers.WITHER, (Object)WitherBossModel.createBodyLayer(CubeDeformation.NONE));
        builder.put((Object)ModelLayers.WITHER_ARMOR, (Object)WitherBossModel.createBodyLayer(INNER_ARMOR_DEFORMATION));
        builder.put((Object)ModelLayers.WITHER_SKULL, (Object)WitherSkullRenderer.createSkullLayer());
        MeshTransformer meshTransformer5 = MeshTransformer.scaling(1.2f);
        builder.put((Object)ModelLayers.WITHER_SKELETON, (Object)layerDefinition27.apply(meshTransformer5));
        ModelLayers.WITHER_SKELETON_ARMOR.putFrom(armorModelSet.map(layerDefinition -> layerDefinition.apply(meshTransformer5)), (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)builder);
        builder.put((Object)ModelLayers.WITHER_SKELETON_SKULL, (Object)layerDefinition3);
        builder.put((Object)ModelLayers.WOLF, (Object)layerDefinition44);
        builder.put((Object)ModelLayers.WOLF_ARMOR, (Object)layerDefinition45);
        builder.put((Object)ModelLayers.WOLF_BABY, (Object)layerDefinition44.apply(WolfModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.WOLF_BABY_ARMOR, (Object)layerDefinition45.apply(WolfModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.ZOGLIN, (Object)layerDefinition25);
        builder.put((Object)ModelLayers.ZOGLIN_BABY, (Object)layerDefinition26);
        builder.put((Object)ModelLayers.ZOMBIE, (Object)layerDefinition2);
        ModelLayers.ZOMBIE_ARMOR.putFrom(armorModelSet, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)builder);
        builder.put((Object)ModelLayers.ZOMBIE_BABY, (Object)layerDefinition2.apply(HumanoidModel.BABY_TRANSFORMER));
        ModelLayers.ZOMBIE_BABY_ARMOR.putFrom(armorModelSet2, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)builder);
        builder.put((Object)ModelLayers.ZOMBIE_HEAD, (Object)layerDefinition21);
        builder.put((Object)ModelLayers.ZOMBIE_HORSE, (Object)layerDefinition4);
        builder.put((Object)ModelLayers.ZOMBIE_HORSE_BABY, (Object)layerDefinition5);
        builder.put((Object)ModelLayers.ZOMBIE_HORSE_SADDLE, (Object)layerDefinition6);
        builder.put((Object)ModelLayers.ZOMBIE_HORSE_BABY_SADDLE, (Object)layerDefinition7);
        builder.put((Object)ModelLayers.ZOMBIE_VILLAGER, (Object)layerDefinition46);
        builder.put((Object)ModelLayers.ZOMBIE_VILLAGER_NO_HAT, (Object)layerDefinition47);
        ArmorModelSet<LayerDefinition> armorModelSet7 = ZombieVillagerModel.createArmorLayerSet(INNER_ARMOR_DEFORMATION, OUTER_ARMOR_DEFORMATION);
        ModelLayers.ZOMBIE_VILLAGER_ARMOR.putFrom(armorModelSet7, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)builder);
        builder.put((Object)ModelLayers.ZOMBIE_VILLAGER_BABY, (Object)layerDefinition46.apply(HumanoidModel.BABY_TRANSFORMER));
        builder.put((Object)ModelLayers.ZOMBIE_VILLAGER_BABY_NO_HAT, (Object)layerDefinition47.apply(HumanoidModel.BABY_TRANSFORMER));
        ModelLayers.ZOMBIE_VILLAGER_BABY_ARMOR.putFrom(armorModelSet7.map(layerDefinition -> layerDefinition.apply(HumanoidModel.BABY_TRANSFORMER)), (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)builder);
        builder.put((Object)ModelLayers.ZOMBIFIED_PIGLIN, (Object)layerDefinition19);
        ModelLayers.ZOMBIFIED_PIGLIN_ARMOR.putFrom(armorModelSet4, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)builder);
        builder.put((Object)ModelLayers.ZOMBIFIED_PIGLIN_BABY, (Object)layerDefinition19.apply(HumanoidModel.BABY_TRANSFORMER));
        ModelLayers.ZOMBIFIED_PIGLIN_BABY_ARMOR.putFrom(armorModelSet5, (ImmutableMap.Builder<ModelLayerLocation, LayerDefinition>)builder);
        builder.put((Object)ModelLayers.BAMBOO_RAFT, (Object)RaftModel.createRaftModel());
        builder.put((Object)ModelLayers.BAMBOO_CHEST_RAFT, (Object)RaftModel.createChestRaftModel());
        LayerDefinition layerDefinition55 = BoatModel.createBoatModel();
        LayerDefinition layerDefinition56 = BoatModel.createChestBoatModel();
        builder.put((Object)ModelLayers.OAK_BOAT, (Object)layerDefinition55);
        builder.put((Object)ModelLayers.OAK_CHEST_BOAT, (Object)layerDefinition56);
        builder.put((Object)ModelLayers.SPRUCE_BOAT, (Object)layerDefinition55);
        builder.put((Object)ModelLayers.SPRUCE_CHEST_BOAT, (Object)layerDefinition56);
        builder.put((Object)ModelLayers.BIRCH_BOAT, (Object)layerDefinition55);
        builder.put((Object)ModelLayers.BIRCH_CHEST_BOAT, (Object)layerDefinition56);
        builder.put((Object)ModelLayers.JUNGLE_BOAT, (Object)layerDefinition55);
        builder.put((Object)ModelLayers.JUNGLE_CHEST_BOAT, (Object)layerDefinition56);
        builder.put((Object)ModelLayers.ACACIA_BOAT, (Object)layerDefinition55);
        builder.put((Object)ModelLayers.ACACIA_CHEST_BOAT, (Object)layerDefinition56);
        builder.put((Object)ModelLayers.CHERRY_BOAT, (Object)layerDefinition55);
        builder.put((Object)ModelLayers.CHERRY_CHEST_BOAT, (Object)layerDefinition56);
        builder.put((Object)ModelLayers.DARK_OAK_BOAT, (Object)layerDefinition55);
        builder.put((Object)ModelLayers.DARK_OAK_CHEST_BOAT, (Object)layerDefinition56);
        builder.put((Object)ModelLayers.PALE_OAK_BOAT, (Object)layerDefinition55);
        builder.put((Object)ModelLayers.PALE_OAK_CHEST_BOAT, (Object)layerDefinition56);
        builder.put((Object)ModelLayers.MANGROVE_BOAT, (Object)layerDefinition55);
        builder.put((Object)ModelLayers.MANGROVE_CHEST_BOAT, (Object)layerDefinition56);
        LayerDefinition layerDefinition57 = SignRenderer.createSignLayer(true);
        LayerDefinition layerDefinition58 = SignRenderer.createSignLayer(false);
        WoodType.values().forEach(woodType -> {
            builder.put((Object)ModelLayers.createStandingSignModelName(woodType), (Object)layerDefinition57);
            builder.put((Object)ModelLayers.createWallSignModelName(woodType), (Object)layerDefinition58);
            for (HangingSignRenderer.AttachmentType attachmentType : HangingSignRenderer.AttachmentType.values()) {
                LayerDefinition layerDefinition3 = HangingSignRenderer.createHangingSignLayer(attachmentType);
                builder.put((Object)ModelLayers.createHangingSignModelName(woodType, attachmentType), (Object)layerDefinition3);
            }
        });
        ImmutableMap immutableMap = builder.build();
        List list = ModelLayers.getKnownLocations().filter(modelLayerLocation -> !immutableMap.containsKey((Object)modelLayerLocation)).toList();
        if (!list.isEmpty()) {
            throw new IllegalStateException("Missing layer definitions: " + String.valueOf(list));
        }
        return immutableMap;
    }
}

